version: 1

accounts:
  - name: iqbal
    coins: ["1000000000stake"]
  - name: rakhan
    coins: ["1000000000stake"]
  - name: prayta
    coins: ["1000000000stake"]
  - name: naufal
    coins: ["1000000000stake"]

validator:
  name: iqbal
  staked: "100000000stake"

client:
  openapi:
    path: "docs/static/openapi.yml"

faucet:
  name: bob
  coins: ["100stake"]
